language: python 
python:
- "3.3"
- "3.4"
install:
- pip install simplejson
script:
- python -m unittest test_ShippingLogicUnitTest -v
- python -m unittest test_SaleItemUnitTest -v
>>>>>>> upstream/master
